In [2]:
#Mengimport library-library yang dibutuhkan 
import matplotlib.pyplot as plt #penggambaran
import numpy as np # Untuk perhitungan algebra
import pandas as pd # memproses data, CSV file I/O (e.g. pd.read_csv)
from sklearn.preprocessing import normalize #Library untuk machine learning
import keras #library untuk neural net
import pandas as pd #loading data dalam bentuk tabel  
import seaborn as sns #penggambaran

AttributeError: module 'tensorflow.core.framework.types_pb2' has no attribute 'SerializedDType'

In [8]:
#Reading data 
data=pd.read_csv("Dataset/iris.csv")
print("Describing the data: ",data.describe())
print("Info of the data:",data.info())

Describing the data:         sepal_length  sepal_width  petal_length  petal_width
count    150.000000   150.000000    150.000000   150.000000
mean       5.843333     3.054000      3.758667     1.198667
std        0.828066     0.433594      1.764420     0.763161
min        4.300000     2.000000      1.000000     0.100000
25%        5.100000     2.800000      1.600000     0.300000
50%        5.800000     3.000000      4.350000     1.300000
75%        6.400000     3.300000      5.100000     1.800000
max        7.900000     4.400000      6.900000     2.500000
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype  
---  ------        --------------  -----  
 0   sepal_length  150 non-null    float64
 1   sepal_width   150 non-null    float64
 2   petal_length  150 non-null    float64
 3   petal_width   150 non-null    float64
 4   species       150 non-null    object 
dtypes: float64(4), object(1)
mem

In [9]:
print("10 first samples of the dataset:",data.head(10))
print("10 last samples of the dataset:",data.tail(10))

10 first samples of the dataset:    sepal_length  sepal_width  petal_length  petal_width      species
0           5.1          3.5           1.4          0.2  Iris-setosa
1           4.9          3.0           1.4          0.2  Iris-setosa
2           4.7          3.2           1.3          0.2  Iris-setosa
3           4.6          3.1           1.5          0.2  Iris-setosa
4           5.0          3.6           1.4          0.2  Iris-setosa
5           5.4          3.9           1.7          0.4  Iris-setosa
6           4.6          3.4           1.4          0.3  Iris-setosa
7           5.0          3.4           1.5          0.2  Iris-setosa
8           4.4          2.9           1.4          0.2  Iris-setosa
9           4.9          3.1           1.5          0.1  Iris-setosa
10 last samples of the dataset:      sepal_length  sepal_width  petal_length  petal_width         species
140           6.7          3.1           5.6          2.4  Iris-virginica
141           6.9          3

In [10]:
sns.lmplot('sepal_length', 'sepal_width',
           data=data,
           fit_reg=False,
           hue="species",
           scatter_kws={"marker": "D",
                        "s": 50})
plt.title('SepalLength vs SepalWidth')

sns.lmplot('petal_length', 'petal_width',
           data=data,
           fit_reg=False,
           hue="species",
           scatter_kws={"marker": "D",
                        "s": 50})
plt.title('PetalLength vs PetalWidth')

sns.lmplot('sepal_length', 'sepal_width',
           data=data,
           fit_reg=False,
           hue="species",
           scatter_kws={"marker": "D",
                        "s": 50})
plt.title('SepalLength vs PetalLength')

sns.lmplot('petal_length', 'petal_width',
           data=data,
           fit_reg=False,
           hue="species",
           scatter_kws={"marker": "D",
                        "s": 50})
plt.title('SepalWidth vs PetalWidth')
plt.show()

NameError: name 'sns' is not defined

In [11]:
print(data["species"].unique())

['Iris-setosa' 'Iris-versicolor' 'Iris-virginica']


In [12]:
data.loc[data["species"]=="Iris-setosa","species"]=2
data.loc[data["species"]=="Iris-versicolor","species"]=0
data.loc[data["species"]=="Iris-virginica","species"]=1
print(data.head())

   sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2       2
1           4.9          3.0           1.4          0.2       2
2           4.7          3.2           1.3          0.2       2
3           4.6          3.1           1.5          0.2       2
4           5.0          3.6           1.4          0.2       2


In [13]:
data=data.iloc[np.random.permutation(len(data))]
print(data.head())

     sepal_length  sepal_width  petal_length  petal_width species
121           5.6          2.8           4.9          2.0       1
50            7.0          3.2           4.7          1.4       0
88            5.6          3.0           4.1          1.3       0
93            5.0          2.3           3.3          1.0       0
76            6.8          2.8           4.8          1.4       0


In [14]:
X=data.iloc[:,0:4].values
y=data.iloc[:,4].values

print("Bentuk dari X",X.shape)
print("Bentuk dari y",y.shape)
print("Contoh dari X\n",X[:3])
print("Contoh dari y\n",y[:3])

Bentuk dari X (150, 4)
Bentuk dari y (150,)
Contoh dari X
 [[5.6 2.8 4.9 2. ]
 [7.  3.2 4.7 1.4]
 [5.6 3.  4.1 1.3]]
Contoh dari y
 [1 0 0]


In [15]:
X_normalized=normalize(X,axis=1)
print("Examples of X_normalised\n",X_normalized[:4])

Examples of X_normalised
 [[0.68307923 0.34153961 0.59769433 0.24395687]
 [0.76701103 0.35063361 0.51499312 0.15340221]
 [0.72992443 0.39103094 0.53440896 0.16944674]
 [0.76986879 0.35413965 0.5081134  0.15397376]]


In [16]:
#Creating train,test and validation data
'''
75% -- train data
25% -- test data
'''
total_length=len(data)
train_length=int(0.75*total_length)
test_length=int(0.25*total_length)

X_train=X_normalized[:train_length]
X_test=X_normalized[train_length:]
y_train=y[:train_length]
y_test=y[train_length:]

print("Length of train set x:",X_train.shape[0],"y:",y_train.shape[0])
print("Length of test set x:",X_test.shape[0],"y:",y_test.shape[0])

Length of train set x: 112 y: 112
Length of test set x: 38 y: 38


In [17]:
#Model Neural Network
from keras.models import Sequential 
from keras.layers import Dense,Activation,Dropout 
from tensorflow.keras.layers import BatchNormalization 
from keras.utils import np_utils

TypeError: Unable to convert function return value to a Python type! The signature was
	() -> handle

In [18]:
#Ubah label ke vector berikutnya
'''
[0]--->[1 0 0]
[1]--->[0 1 0]
[2]--->[0 0 1]
'''
y_train=np_utils.to_categorical(y_train,num_classes=3)
y_test=np_utils.to_categorical(y_test,num_classes=3)
print("Shape of y_train",y_train.shape)
print("Shape of y_test",y_test.shape)

NameError: name 'np_utils' is not defined

In [19]:
model=Sequential()
model.add(Dense(1000,input_dim=4,activation='relu'))
model.add(Dense(16,activation='relu'))
model.add(Dense(16,activation='relu'))
model.add(Dropout(0.2))
model.add(Dense(3,activation='softmax'))
model.compile(loss='categorical_crossentropy',optimizer='adam',metrics=['accuracy'])

NameError: name 'Sequential' is not defined

In [20]:
model.summary()

NameError: name 'model' is not defined

In [21]:
model.fit(X_train,y_train,validation_data=(X_test,y_test),batch_size=100,epochs=20,verbose=1)

NameError: name 'model' is not defined

In [22]:
prediction=model.predict(X_test)
length=len(prediction)
y_label=np.argmax(y_test,axis=1)
predict_label=np.argmax(prediction,axis=1)

accuracy=np.sum(y_label==predict_label)/length * 100 
print("Accuracy of the dataset",accuracy )

NameError: name 'model' is not defined

In [23]:
from sklearn.metrics import classification_report, confusion_matrix
predictions = np.argmax(model.predict(X_test), axis = 1)
Y_test = np.argmax(y_test, axis =1)
print(confusion_matrix(Y_test, predictions))
print(classification_report(Y_test, predictions))

NameError: name 'model' is not defined